version: '3.8'

services:
  clip-api-dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - ENVIRONMENT=development
    volumes:
      # Mapeia o código local para o container (hot reload)
      - .:/app
      # Cache de modelos para evitar download repetido
      - model_cache:/root/.cache
      # Logs da aplicação
      - ./logs:/app/logs
      # Pasta estática para imagens salvas
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  model_cache: 